### ISSUE TITLE
Regarding addition of Future goals of the project.

### ISSUE THREAD

**Issue by pranjultiwari** [shantanu-mishraa/Diabetes-Prediction#1]
_Hello there!_
You must add a paragraph in your readme file about the **future** of this project.
It is a Machine learning model which could be made more creative if we deploy this project on the web by using Flask.

**Comment by pranjultiwari** [comment]
The issue was resolved.

**Comment by hellomishraa** [comment]
We will deploy this Project either by using Flask or Streamlit, streamlit will be relatively easier than Flask.
